Book an appointment Front-end: Navigation
AyoubM490/book-an-appointment-front-end pull request #4
Opened 2022-08-17 14:59 UTC by Debas-31

## Book an appointment Front-end: Navigation
>In this future branch, implemented :
- [x] The user to navigate through the following links
  - Motorcycles that you selected as a theme.
  - Reservation
  - My reservations
  - Add a motorcycle

2022-08-17 18:54 UTC, AyoubMs commented
Please fix the linter errors

2022-08-18 10:56 UTC, Achilles-Dev requested changes
Hi @Debas-31 :wave:

Good job implementing the design guidelines.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_See the inline comments below for more required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

2022-08-18 10:56 UTC, Achilles-Dev commented on src/layout/navigation/Sidebar.js
> +        <NavLink to="#" activeClassName="active" className="nav-link p-3">ADD MOTORCYCLE</NavLink>
Links on the nav.

- [ ] Motorcycles
- [ ]  "Reserve" form.
- [ ]  My reservations.
- [ ]  Add motorcycle
- [ ]  Delete motorcycle

Please make sure your navigation links have the above names.

2022-08-18 21:15 UTC, sentayhu19 approved these changes
Hi @Debas-31 -Dev
# Status: Approved ✔️ ✔️ ✔️ 
 
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/156831571-196c349c-f704-43b1-ab81-9fd7a6acfb0e.gif)

👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_Check for optional comments below_

Cheers and Happy coding!👏👏👏

2022-08-19 05:19 UTC, merged